version: '3.5'

services:
  mariadb:
    build:
      context: ./mariaDB
      dockerfile: Dockerfile
    container_name: mariaDB
    volumes:
      - container-volume:/var/lib/mysql
      - ./mariaDB/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: always
    hostname: mariaDB
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=master_root_password
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=admin
      - MARIADB_DATABASE=app
      - ALLOW_EMPTY_PASSWORD=yes

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    hostname: phpmyadmin
    depends_on:
      - mariadb
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 5050:80

  mongo:
    build:
      context: ./mongoDB
      dockerfile: Dockerfile
    container_name: mongodb
    restart: always
    hostname: mongodb
    ports:
      - 27017:27017
      - 28017:28017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongodb

  qmanager-authentication-service:
    container_name: qmanager-authentication-service
    stdin_open: true
    hostname: auth-service
    depends_on:
      - mariadb
    tty: true
    build:
      context: ./qmanager-authentication-service
      dockerfile: Dockerfile
    ports:
      - 5000:5000
volumes:
  container-volume:

