version: '3.5'

services:
  qmanager-authentication-service:
    container_name: qmanager-authentication-service
    stdin_open: true
    tty: true
    build:
      context: qmanager-authentication-service
      dockerfile: Dockerfile
    ports:
      - 5000:5000

  mariadb:
    container_name: mariaDB
    image: bitnami/mariadb:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=master_root_password
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=admin
      - MARIADB_DATABASE=db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    restart: always
    ports:
      - 5050:80
